AlienProject/Models/Killing.cs
using System;
using System.Collections.Generic;

namespace AlienProject.Models
{
    public partial class Killing
    {
        public int KillingId { get; set; }
        public DateTime KillingDate { get; set; }
        public int? HumanId { get; set; }
        public int? AlienId { get; set; }

        public virtual Alien? Alien { get; set; }
        public virtual Human? Human { get; set; }
    }
}

AlienProject/Models/KillingViewModel.cs
namespace AlienProject.Models
{
    public class KillingViewModel
    {
        public int KillingId { get; set; }
        public DateTime KillingDate { get; set; }
        public int? HumanId { get; set; }
        public int? AlienId { get; set; }
        public string AlienName { get; set; }
        public DateTime? AlienBirthDate { get; set; }
        public string AlienEmail { get; set; }
        public string HumanName { get; set; }
        public DateTime? HumanBirthDate { get; set; }
        public string HumanEmail { get; set; }
    }
}

AlienProject/Controllers/KillingController.cs
using AlienProject.GenerateTables;
using AlienProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace AlienProject.Controllers
{
    public class KillingController : Controller
    {
        private readonly AlienDbContext _context;

        public KillingController(AlienDbContext context)
        {
            this._context = context;
        }
        public IActionResult Killing()
        {
            Generate generate = new(_context);
            var viewModelList = generate.GenerateKillingTable();
            return View(viewModelList); ;
        }

        [HttpGet]
        public IActionResult FindAlien()
        {
            return View();
        }
        [HttpPost]
        public IActionResult FindAlien(string humanName,DateTime fromDate, DateTime toDate)
        {
            Generate generate = new(_context);
            var kills = generate.GenerateKillingTable();
            var killedAlien = kills
                .Where(a => a.HumanName == humanName && a.KillingDate >= fromDate && a.KillingDate <= toDate)
                .ToList();

            return View(killedAlien);
        }

    }
}

AlienProject/Views/Killing/FindAlien.cshtml
@model List<KillingViewModel>

<!DOCTYPE html>
<html>
<head>
    <title>Find Killed Alien</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>

    <div class="container">
        <h1 class="pt-4 mb-4">Find Alien</h1>

        <form asp-controller="Killing" asp-action="FindAlien" method="post" class="mb-4">
            <div class="form-group">
                <label for="alienName">Human Name:</label>
                <input type="text" name="humanName" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="fromDate">From Date:</label>
                <input type="date" name="fromDate" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="toDate">To Date:</label>
                <input type="date" name="toDate" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-success bg-color">Find Alien</button>
            <a class="btn btn-secondary" asp-action="Killing">Back</a>
        </form>

        @if (Model != null)
        {
            if (Model.Any())
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th>Killing Date</th>
                            <th>Alien Name</th>
                            <th>Alien Birth Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.KillingDate.ToShortDateString()</td>
                                <td>@item.AlienName</td>
                                <td>@(item.AlienBirthDate.HasValue ? item.AlienBirthDate.Value.ToShortDateString() : "-")</td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p class="mt-4">No alien found.</p>
            }
        }
    </div>

</body>
</html>

AlienProject/Views/Killing/Killing.cshtml
@model List<KillingViewModel>

<!DOCTYPE html>
<html>
<head>
    <title>Killings</title>
    <style>
                   
            
                    .container {
                        padding: 20px;
                        color: white;
                        
                    }
                    
            
                   h2 {
                                           color: #21E786; 
                                           font-size: 47px;
                                           font-weight: 800;
                                       }
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        border-radius: 15px;
                        margin-top: 20px;
                    }
            
                    th, td {
                        border: 1px solid gray;
                        padding: 10px;
                        text-align: left;
                    }
            
                    
            
                    tr:hover {
                        background-color: #056235;
                        transition: ease-in-out;
                        duration: 500ms;
                    }
                </style>
</head>
<body>
<div class="container">
    <h2>Killings</h2>
    
    <table class="table text-white">
        <thead>
        <tr>
            <th>Killing Id</th>
            <th>Killing Date</th>
            <th>Alien Name</th>
            <th>Alien Birth Date</th>
            <th>Human Name</th>
            <th>Human Birth Date</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.KillingId</td>
                <td>@item.KillingDate.ToShortDateString()</td>
                <td>@item.AlienName</td>
                <td>@(item.AlienBirthDate.HasValue ? item.AlienBirthDate.Value.ToShortDateString() : "-")</td>
                <td>@item.HumanName</td>
                <td>@(item.HumanBirthDate.HasValue ? item.HumanBirthDate.Value.ToShortDateString() : "-")</td>
            </tr>
        }
            
        </tbody>
    </table>
   
</div>
</body>
</html>

@if (User.Identity.IsAuthenticated)
{
    <div class="container">
    <ul>
        <li><a class="text-color" asp-action="FindAlien">Find Killed Alien</a></li>
    </ul>
    </div>  
}