AlienProject/Models/Human.cs
using System;
using System.Collections.Generic;

namespace AlienProject.Models
{
    public partial class Human
    {
        public Human()
        {
            Abductions = new HashSet<Abduction>();
            Excursions = new HashSet<Excursion>();
            Experiments = new HashSet<Experiment>();
            Killings = new HashSet<Killing>();
            SpaceshippVisits = new HashSet<SpaceshippVisit>();
        }

        public int HumanId { get; set; }
        public string Name { get; set; } = null!;
        public DateTime? BirthDate { get; set; }
        public string Email { get; set; } = null!;
        public string Password { get; set; } = null!;

        public virtual ICollection<Abduction> Abductions { get; set; }
        public virtual ICollection<Excursion> Excursions { get; set; }
        public virtual ICollection<Experiment> Experiments { get; set; }
        public virtual ICollection<Killing> Killings { get; set; }
        public virtual ICollection<SpaceshippVisit> SpaceshippVisits { get; set; }
    }
}

AlienProject/Controllers/AlienController.cs
using AlienProject.Additional;
using AlienProject.GenerateTables;
using AlienProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace AlienProject.Controllers
{
    public class AlienController : Controller
    {
        private readonly AlienDbContext _context;

        public AlienController(AlienDbContext context) {
            this._context = context;
        }
        public IActionResult Aliens()
        {
            var aliens = _context.Aliens;
            return View(aliens);
        }
        [HttpGet]
        public IActionResult FindCommon() {
            return View();
        }

        [HttpPost]
        public IActionResult FindCommon(string alienName, string humanName, DateTime fromDate, DateTime toDate) {
            Generate generate = new(_context);
            var excursions = generate.GenerateExcursionTable();
            var experiments = generate.GenerateExperimentsTable();
            var commonExcursions = excursions
       .Where(excursion => excursion.AlienName == alienName && excursion.HumanName == humanName
           && excursion.ExcursionDate >= fromDate && excursion.ExcursionDate <= toDate)
       .Select(excursion => new CommonActivityViewModel
       {
           ActivityId = excursion.ExcursionId,
           ActivityDate = excursion.ExcursionDate,
           AlienName = excursion.AlienName,
           AlienBirthDate = excursion.AlienBirthDate,
           AlienEmail = excursion.AlienEmail,
           HumanName = excursion.HumanName,
           HumanBirthDate = excursion.HumanBirthDate,
           HumanEmail = excursion.HumanEmail,
           Type = "Excursion"
       })
       .ToList();

            var commonExperiments = experiments
                .Where(experiment => experiment.AlienName == alienName && experiment.HumanName == humanName
                    && experiment.ExperimentDate >= fromDate && experiment.ExperimentDate <= toDate)
                .Select(experiment => new CommonActivityViewModel
                {
                    ActivityId = experiment.ExperimentId,
                    ActivityDate = experiment.ExperimentDate,
                    AlienName = experiment.AlienName,
                    AlienBirthDate = experiment.AlienBirthDate,
                    AlienEmail = experiment.AlienEmail,
                    HumanName = experiment.HumanName,
                    HumanBirthDate = experiment.HumanBirthDate,
                    HumanEmail = experiment.HumanEmail,
                    Type = "Experiment"
                })
                .ToList();

            var commonActivities = commonExcursions.Concat(commonExperiments).ToList();
            return View(commonActivities);

        }
        [HttpGet]
        public IActionResult Add() {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Alien alien) {
            if (alien == null)
            {
                return View();
            }


            _context.Aliens.Add(alien);
            _context.SaveChanges();
            return RedirectToAction("Aliens");
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var alien = _context.Aliens.Where(s => s.AlienId == Id).FirstOrDefault();

            return View(alien);

        }
        [HttpPost]
        public IActionResult Edit(Alien alien)
        {
            if (alien == null) {
                return NotFound();
            }
            _context.Aliens.Update(alien);
            _context.SaveChanges();
            return RedirectToAction("Aliens");
        }
    }
}

AlienProject/Controllers/HumanController.cs
using AlienProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AlienProject.Controllers
{
    public class HumanController : Controller
    {
        private readonly AlienDbContext _context;

        public HumanController(AlienDbContext context)
        {
            this._context = context;
        }
        public IActionResult Humans()
        {
            var humans= _context.Humans;
            return View(humans);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Human human)
        {
            if (human == null)
            {
                return View();
            }

            _context.Humans.Add(human);
            _context.SaveChanges();
            return RedirectToAction("Aliens");
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var human = _context.Humans.Where(s => s.HumanId == Id).FirstOrDefault();

            return View(human);

        }
        [HttpPost]
        public IActionResult Edit(Human human)
        {
            if (human == null)
            {
                return NotFound();
            }
            _context.Humans.Update(human);
            _context.SaveChanges();
            return RedirectToAction("Humans");
        }

    }
}

AlienProject/Views/Human/Add.cshtml
@model AlienProject.Models.Human

@{
    ViewData["Title"] = "Add";
}

<div class="container pt-5">
    <h1 class="text-center">Add</h1>

    <h4 class="text-center">Human</h4>
    <hr />

    <div class="row justify-content-center">
        <div class="col-md-4">
            <form asp-action="Add">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="HumanId" class="control-label"></label>
                    <input asp-for="HumanId" class="form-control"/>
                    <span asp-validation-for="HumanId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="BirthDate" class="control-label"></label>
                    <input asp-for="BirthDate" class="form-control"/>
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control"/>
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control"/>
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>

                <div class="form-group text-center mt-3">
                    <input  type="submit" value="Create" class="btn btn-success bg-color"/>
                </div>
            </form>
        </div>
    </div>

    <div class="text-center mt-3">
        <a asp-action="Humans" class="btn btn-secondary">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlienProject/Views/Human/Edit.cshtml
@model AlienProject.Models.Human

@{
    ViewData["Title"] = "Edit";
}

<div class="container pt-5">
    <h1 class="text-center">Edit</h1>

    <h4 class="text-center">Human</h4>
    <hr />

    <div class="row justify-content-center">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="HumanId" />

                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="BirthDate" class="control-label"></label>
                    <input asp-for="BirthDate" class="form-control" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>

                <div class="form-group text-center mt-3">
                    <input type="submit" value="Save" class="btn btn-success bg-color" />
                </div>
            </form>
        </div>
    </div>

    <div class="text-center mt-3">
        <a asp-action="Humans" class="btn btn-secondary">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlienProject/Views/Human/Humans.cshtml
@model IEnumerable<AlienProject.Models.Human>

@{
    ViewData["Title"] = "Humans";
}
<head>
    
    <style>
               
        
                .container {
                    padding: 20px;
                }
        
               h2 {
                   color: #21E786; 
                   font-size: 47px;
                   font-weight: 800;
                   }
        
                table {
                    width: 100%;
                    border-collapse: collapse;
                    border-radius: 15px;
                    margin-top: 20px;
                }
        
                th, td {
                    border: 1px solid gray;
                    padding: 10px;
                    text-align: left;
                }
        
                
        
                tr:hover {
                    background-color: #056235;
                    transition: ease-in-out;
                    duration: 500ms;
                }
            </style>
</head>
<div class="container">
    <h2>Humans</h2>

    <table class="table text-white">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HumanId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
    
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.HumanId</td>
                <td>@item.Name</td>
                <td>@(item.BirthDate.HasValue ? item.BirthDate.Value.ToShortDateString() : "-")</td>
                <td>@item.Email</td>
                <td>
                    <a class="text-color-white" asp-action="Edit" asp-route-id="@item.HumanId">Edit</a>
                </td>
            </tr>
        }
        </tbody>
    </table>



    <ul>
        <li>
        <a class="text-color" asp-action="Add">
            Add
        </a>
        </li>
        <li><a class="text-color" asp-action="FindCommon" asp-controller="Alien">Find Common Experiments and Excursions</a></li>
    </ul>
</div>