AlienProject/Models/SpaceShipViewModel.cs
namespace AlienProject.Models
{
    public class SpaceshipViewModel
    {
        public int SpaceshipVisitId { get; set; }
        public int? SpaceshipId { get; set; }
        public DateTime SpaceshipVisitDate { get; set; }
        public int? HumanId { get; set; }
        public string HumanName { get; set; }
        public string SpaceshipName { get; set; }
    }
}

AlienProject/Controllers/SpaceShipController.cs
using AlienProject.Additional;
using AlienProject.GenerateTables;
using AlienProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AlienProject.Controllers
{
    public class SpaceShipController : Controller
    {
        private readonly AlienDbContext _context;

        public SpaceShipController(AlienDbContext context) {
            this._context = context;
        }
        public IActionResult SpaceShips()
        {
            var spaceShips = _context.Spaceshipps.ToList();
            return View(spaceShips);
        }
        [HttpGet]
        public IActionResult FindPeople() {
            return View();
        }
        [HttpPost]
        public IActionResult FindPeople(string humanName, DateTime fromDate, DateTime toDate) {
            Generate generate = new(_context);
            var data = generate.GenerateSpaceShipTable();
            var spaceshipsVisited = data
            .Where(visit => visit.HumanName == humanName && visit.SpaceshipVisitDate >= fromDate && visit.SpaceshipVisitDate <= toDate)
            .Select(visit => visit.SpaceshipName)
            .ToList();
            return View(spaceshipsVisited);
        }

        [HttpGet]
        public IActionResult ExperimentsPerShip()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ExperimentsPerShip(string alienName, DateTime fromDate, DateTime toDate)
        {
            List<ShipInfo> shipsInfo = GetShipsInfo(alienName, fromDate, toDate);
            return View(shipsInfo);
        }

        private List<ShipInfo> GetShipsInfo(string alienName, DateTime fromDate, DateTime toDate)
        {
            var shipsInfo = _context.SpaceshipExperiments
                .Where(se => se.Experiment.Alien.Name == alienName && se.Experiment.ExperimentDate >= fromDate && se.Experiment.ExperimentDate <= toDate)
                .GroupBy(se => se.SpaceshipId)
                .Select(g => new ShipInfo
                {
                    ShipId = g.Key,
                    ShipName = g.Max(se => se.Spaceship.SpaceshipName),
                    ExperimentCount = g.Count()
                })
                .OrderByDescending(info => info.ExperimentCount)
                .ToList();

            return shipsInfo;
        }

        [HttpGet]
        public IActionResult Add() {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Spaceshipp spaceship)
        {
            if (spaceship == null)
            {
                return View();
            }
            _context.Spaceshipps.Add(spaceship);
            _context.SaveChanges(); 
            return RedirectToAction("SpaceShips");
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var ship = _context.Spaceshipps.Where(s => s.SpaceshipId == Id).FirstOrDefault();

            return View(ship);

        }
        [HttpPost]
        public IActionResult Edit(Spaceshipp spaceshipp)
        {
            if (spaceshipp == null)
            {
                return NotFound();
            }
            _context.Spaceshipps.Update(spaceshipp);
            _context.SaveChanges();
            return RedirectToAction("SpaceShips");
        }

    }
}

AlienProject/Views/SpaceShip/Add.cshtml
@model AlienProject.Models.Spaceshipp

@{
    ViewData["Title"] = "Add";
}


<div class="container pt-5">
    <h1 class="text-center">Add</h1>

    <h4 class="text-center">Spaceshipp</h4>
    <hr />

    <div class="row justify-content-center">


    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SpaceshipId" class="control-label"></label>
                <input asp-for="SpaceshipId" class="form-control" />
                <span asp-validation-for="SpaceshipId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpaceshipName" class="control-label"></label>
                <input asp-for="SpaceshipName" class="form-control" />
                <span asp-validation-for="SpaceshipName" class="text-danger"></span>
            </div>
            <div class="form-group text-center mt-3">
                <input type="submit" value="Create" class="btn btn-success bl-color" />
                 <a class="btn btn-secondary" asp-action="SpaceShips">Back to List</a>
                
            </div>
            
        </form>
    </div>
</div>
</div>

<div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlienProject/Views/SpaceShip/Edit.cshtml
@model AlienProject.Models.Spaceshipp

@{
    ViewData["Title"] = "Edit";
}
<div class="container pt-5">
<h1 class="text-center">Edit</h1>

<h4 class="text-center">Spaceshipp</h4>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SpaceshipId" />
            <div class="form-group">
                <label asp-for="SpaceshipName" class="control-label"></label>
                <input asp-for="SpaceshipName" class="form-control" />
                <span asp-validation-for="SpaceshipName" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-center align-items-center pt-3">
                <input type="submit" value="Save" class="btn btn-success bg-color m-1" />
                <a class="btn btn-secondary m-1" asp-action="SpaceShips">Back to List</a>
                
            </div>
        </form>
    </div>
</div>

<div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlienProject/Views/SpaceShip/ExperimentsPerShip.cshtml
@model List<AlienProject.Additional.ShipInfo>

<!DOCTYPE html>
<html>
<head>
    <title>Experiments Per Ship</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>

    <div class="container">
        <h1 class="pt-4 mb-4">Experiments Per Ship</h1>

        <form asp-controller="SpaceShip" asp-action="ExperimentsPerShip" method="post" class="mb-4">
            <div class="form-group">
                <label for="alienName">Alien Name:</label>
                <input type="text" name="alienName" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="fromDate">From Date:</label>
                <input type="date" name="fromDate" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="toDate">To Date:</label>
                <input type="date" name="toDate" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-success bg-color">Get Experiments Per Ship</button>
        </form>

        @if (Model != null)
        {
            if (Model.Any())
            {
                <table class="table text-white">
                    <thead>
                        <tr>
                            <th>Ship Name</th>
                            <th>Experiment Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var shipInfo in Model)
                        {
                            <tr >
                                <td>@shipInfo.ShipName</td>
                                <td>@shipInfo.ExperimentCount</td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p class="pt-4">No ships found for the specified criteria.</p>
            }
        }
    </div>

</body>
</html>

AlienProject/Views/SpaceShip/FindPeople.cshtml
@model List<string>

<!DOCTYPE html>
<html>
<head>
    <title>Spaceships Visited by Human</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>

    <div class="container">
        <h1 class="pt-4 mb-4">Spaceships Visited by Human</h1>

        <form asp-controller="SpaceShip" asp-action="FindPeople" method="post" class="mb-4">
            <div class="form-group">
                <label for="humanId">Human Name:</label>
                <input type="text" name="humanName" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="fromDate">From Date:</label>
                <input type="date" name="fromDate" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="toDate">To Date:</label>
                <input type="date" name="toDate" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-success bg-color">Find Spaceships Visited</button>
            <a class="btn btn-secondary" asp-action="SpaceShips">Back</a>
        </form>

        @if (Model != null)
        {
            if (Model.Any())
            {
                <ul class="list-group">
                    @foreach (var spaceshipName in Model)
                    {
                        <li>@spaceshipName</li>
                    }
                </ul>
            }
            else
            {
                <p class="mt-4">No spaceships visited by the specified human in the given period.</p>
            }
        }
    </div>
</body>
</html>

AlienProject/Views/SpaceShip/SpaceShips.cshtml
@model IEnumerable<AlienProject.Models.Spaceshipp>

@{
    ViewData["Title"] = "SpaceShips";
}

<head>
    <style>
                   
            
                    .container {
                        padding: 20px;
                        color: white;
                    }
            
                    h2 {
                        color: #21E786; 
                        font-size: 47px;
                        font-weight: 800;
                    }
            
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        border-radius: 15px;
                        margin-top: 20px;
                    }
            
                    th, td {
                        border: 1px solid gray;
                        padding: 10px;
                        text-align: left;
                    }
            
                    
            
                    tr:hover {
                        background-color: #056235;
                        transition: ease-in-out;
                        duration: 500ms;
                    }
                </style>
</head>

<div class="container">
<h2>SpaceShips</h2>

<table class="table text-white">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SpaceshipId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpaceshipName)
        </th>
        @if (User.Identity.IsAuthenticated)
                   {
                       <td>
                           
                       </td>
                   }
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SpaceshipId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SpaceshipName)
            </td>
            @if (User.Identity.IsAuthenticated)
            {
                <td>
                    
                    <a class="text-color-white" asp-action="Edit" asp-route-id="@item.SpaceshipId">Edit</a>
                </td>
            }
        </tr>
    }
    </tbody>
</table>
</div>
@if (User.Identity.IsAuthenticated)
{
    <div class="container">
        
   
    
        <ul><li>
            <a class="text-color" asp-action="Add">Add</a></li>
            <li><a class="text-color" asp-action="FindPeople">Find People</a></li>
            <li><a class="text-color" asp-action="ExperimentsPerShip">Find Experiment</a></li>
        </ul>
     </div>
}